/**
 * Audio clip registry (owned by the audio build). Evaluated in two realms (runtime
 * and editor): pure data only. Every clip is generated by
 * `node scripts/synth-audio.mjs` into public/audio/<id>.<mp3|ogg> (file name = id).
 * Loops are Ogg/Opus (gapless; the two beds are stereo); one-shots are mono MP3 (the
 * heartbeat is a one-shot the AudioSystem plays on its own beat clock).
 * `<id>-2`, `<id>-3` … are variants of `<id>` that the AudioSystem rotates. Every
 * clip loads in the background so none blocks `World.create`.
 *
 * Ids share one manifest with items, valley, creatures and UI: 'page' and 'pack-roll'
 * (item prototypes) and 'brazier' (valley) are taken, hence 'sfx-page', 'sfx-pack-roll'
 * and 'brazier-ignite'.
 */
import { AssetType } from '@iwsdk/core';

const url = (path: string) => `${import.meta.env.BASE_URL}${path}`;
const clip = (file: string) => ({ type: AssetType.Audio, url: url(`audio/${file}`), priority: 'background' as const });

export const audioAssets = {
  // Beds and loops
  'forest-day': clip('forest-day.ogg'),
  night: clip('night.ogg'),
  'fire-bed': clip('fire-bed.ogg'),
  'fire-pops': clip('fire-pops.ogg'),
  'torch-flame': clip('torch-flame.ogg'),
  brook: clip('brook.ogg'),
  'beacon-roar': clip('beacon-roar.ogg'),
  'beacon-build': clip('beacon-build.ogg'),
  // Fire and cooking
  'lighter-flick': clip('lighter-flick.mp3'),
  'lid-clink': clip('lid-clink.mp3'),
  ignite: clip('ignite.mp3'),
  'brazier-ignite': clip('brazier-ignite.mp3'),
  plop: clip('plop.mp3'),
  'plop-2': clip('plop-2.mp3'),
  stir: clip('stir.mp3'),
  'bowl-fill': clip('bowl-fill.mp3'),
  eat: clip('eat.mp3'),
  'eat-2': clip('eat-2.mp3'),
  sizzle: clip('sizzle.mp3'),
  'fire-out': clip('fire-out.mp3'),
  smother: clip('smother.mp3'),
  // Crafting, gathering, handling
  'hammer-clank': clip('hammer-clank.mp3'),
  'hammer-clank-2': clip('hammer-clank-2.mp3'),
  'hammer-clank-3': clip('hammer-clank-3.mp3'),
  knock: clip('knock.mp3'),
  'knock-2': clip('knock-2.mp3'),
  'craft-complete': clip('craft-complete.mp3'),
  'bench-ready': clip('bench-ready.mp3'),
  'recipe-learned': clip('recipe-learned.mp3'),
  'invalid-clunk': clip('invalid-clunk.mp3'),
  chop: clip('chop.mp3'),
  'chop-2': clip('chop-2.mp3'),
  'chop-3': clip('chop-3.mp3'),
  'wood-split': clip('wood-split.mp3'),
  'wood-split-2': clip('wood-split-2.mp3'),
  rustle: clip('rustle.mp3'),
  'rustle-2': clip('rustle-2.mp3'),
  'rustle-3': clip('rustle-3.mp3'),
  grab: clip('grab.mp3'),
  'grab-2': clip('grab-2.mp3'),
  'grab-3': clip('grab-3.mp3'),
  drop: clip('drop.mp3'),
  'drop-2': clip('drop-2.mp3'),
  'drop-3': clip('drop-3.mp3'),
  'drop-light': clip('drop-light.mp3'),
  'drop-light-2': clip('drop-light-2.mp3'),
  'drop-light-3': clip('drop-light-3.mp3'),
  snap: clip('snap.mp3'),
  'snap-2': clip('snap-2.mp3'),
  'pack-unroll': clip('pack-unroll.mp3'),
  'sfx-pack-roll': clip('sfx-pack-roll.mp3'),
  'sfx-page': clip('sfx-page.mp3'),
  // Weapons and combat
  'spear-whoosh': clip('spear-whoosh.mp3'),
  hit: clip('hit.mp3'),
  'hit-2': clip('hit-2.mp3'),
  'hit-3': clip('hit-3.mp3'),
  'crossbow-twang': clip('crossbow-twang.mp3'),
  'bolt-thunk': clip('bolt-thunk.mp3'),
  'bolt-thunk-2': clip('bolt-thunk-2.mp3'),
  'reload-click': clip('reload-click.mp3'),
  'dry-click': clip('dry-click.mp3'),
  'sentry-dry': clip('sentry-dry.mp3'),
  'sentry-fire': clip('sentry-fire.mp3'),
  // Creatures and wildlife
  'deer-flee': clip('deer-flee.mp3'),
  'wolf-howl': clip('wolf-howl.mp3'),
  'wolf-howl-2': clip('wolf-howl-2.mp3'),
  'wolf-howl-3': clip('wolf-howl-3.mp3'),
  'wolf-growl': clip('wolf-growl.mp3'),
  'wolf-growl-2': clip('wolf-growl-2.mp3'),
  'wolf-growl-3': clip('wolf-growl-3.mp3'),
  'wolf-bite': clip('wolf-bite.mp3'),
  'wolf-pant': clip('wolf-pant.mp3'),
  'wolf-yelp': clip('wolf-yelp.mp3'),
  'wolf-dissolve': clip('wolf-dissolve.mp3'),
  bird: clip('bird.mp3'),
  'bird-2': clip('bird-2.mp3'),
  'bird-3': clip('bird-3.mp3'),
  'bird-4': clip('bird-4.mp3'),
  'bird-5': clip('bird-5.mp3'),
  'bird-6': clip('bird-6.mp3'),
  owl: clip('owl.mp3'),
  'owl-2': clip('owl-2.mp3'),
  // Player, stingers, music
  'player-hurt': clip('player-hurt.mp3'),
  'player-struck': clip('player-struck.mp3'),
  heartbeat: clip('heartbeat.mp3'),
  'heartbeat-2': clip('heartbeat-2.mp3'),
  'step-grass': clip('step-grass.mp3'),
  'step-grass-2': clip('step-grass-2.mp3'),
  'step-grass-3': clip('step-grass-3.mp3'),
  'step-grass-4': clip('step-grass-4.mp3'),
  'step-dirt': clip('step-dirt.mp3'),
  'step-dirt-2': clip('step-dirt-2.mp3'),
  'step-dirt-3': clip('step-dirt-3.mp3'),
  'step-dirt-4': clip('step-dirt-4.mp3'),
  journey: clip('journey.mp3'),
  sleep: clip('sleep.mp3'),
  dawn: clip('dawn.mp3'),
  dusk: clip('dusk.mp3'),
  'spire-eye': clip('spire-eye.mp3'),
  ending: clip('ending.mp3'),
  death: clip('death.mp3'),
  stage: clip('stage.mp3'),
};

export type ClipId = keyof typeof audioAssets;
