/**
 * Prometheus' shade: every line the guide can speak, what triggers it, and when it
 * still makes sense. Pure data plus pure helpers (no World, DOM, timers or
 * packages): the asset manifest, the GuideSystem, the ToastSystem, the dev-only
 * voice-prep page, scripts/voice-urls.mjs and tests/voice-lines.test.mjs import it.
 *
 * Voice clips are generated by Drawcall (@drawcall/generate). A clip's URL is a
 * content hash of its request ({text, voice, style}). The runtime never computes it:
 * `node scripts/voice-urls.mjs` writes every line's hash into voice-urls.ts (a static
 * module), and tests/voice-lines.test.mjs fails when that file no longer matches the
 * package's computation. Changing a line's text, the voice or the style changes its
 * hash, so the clip must be generated again (voice-prep.html). A line's `hint` is
 * subtitle-only and never part of the request.
 */
import type { GameEvent } from './bus.js';
import { BOLTS_PER_BUNDLE, SENTRY_STARTER_BOLTS } from './recipes.js';

/** The shade's voice. A deep, calm Gemini voice; the style prompt sets the delivery. */
export const VOICE = {
  voice: 'Charon',
  style: 'An ancient Titan speaking softly beside a campfire at night: warm, weathered and unhurried, '
    + 'with quiet gravity and kindness. Low and close to the listener, never theatrical.',
} as const;

/** Same origin rule as the package's dist/origin.js (ORIGIN is not exported). */
export const DRAWCALL_ORIGIN: string = (import.meta.env?.DEV && import.meta.env.VITE_DRAWCALL_GENERATE_URL) || 'https://generate.drawcall.ai';

/** Speaking pace used to estimate a line's length when its clip is missing. */
export const WORDS_PER_SECOND = 2.3;
/** Longest subtitle the panel holds comfortably. */
export const MAX_TEXT = 220;
/** Longest spoken line (estimated seconds). */
export const MAX_SECONDS = 12;
/** Drawcall prepares at most 32 requests per batch; voice-prep.html splits the lines into batches of this size. */
export const PREP_BATCH = 20;

/**
 * Combat discipline: while a live wolf is within `radius` m of the player, or for
 * `hurtQuiet` s after a bite, only lines of `priority` or more may start (death,
 * respawn, the beacon and the ending); a lower line that is speaking is cut.
 */
export const THREAT = { priority: 9, radius: 12, hurtQuiet: 6 } as const;

/**
 * State checks, evaluated by the GuideSystem against the live game when a line's
 * turn comes: `unless` retires a line whose lesson the player already learned;
 * `when` drops a line whose moment has passed (a later trigger may queue it again).
 */
export type GuideCondition =
  | 'fire-lit' // the campfire is burning
  | 'page-read' // any page has been read
  | 'stew-cooked' // a stew waits in the pot, or a meal was eaten
  | 'meal-eaten' // the 'eat-meal' objective is done
  | 'pot-half' // exactly one food waits in the pot, no stew yet
  | 'fed' // hunger is comfortable again
  | 'healed' // health is comfortable again
  | 'whole' // health is (nearly) full
  | 'day' // the day phase (not dusk, night or dawn)
  | 'night' // dusk, night or dawn
  | 'grabbed' // the player has taken hold of something this session
  | 'wolves-stirring' // the danger stage is 1 or more: the Hollow come at night
  | 'at-bench' // the player stands within reach of the crafting bench
  | 'at-camp' // the player is at camp (near the campfire and its pot)
  | 'bench-ready' // the bench bays hold a valid set, not yet struck
  | 'bench-wrong' // the bench bays hold three parts that make nothing
  | 'torch-lit' // the torch objective is done
  | 'sentry-built' // the sentry objective is done
  | 'sentry-dry'; // a deployed sentry has no bolts left

export type GuideLine = {
  /** Unique id; saved in GameState.guide once spoken. */
  readonly id: string;
  /**
   * Trigger keys (see triggersOf and POLLED_TRIGGERS), each optionally delayed:
   * 'crafted:torch', 'done:intro+6' (6 s after the intro finished).
   */
  readonly on: readonly string[];
  /** The spoken words (and the subtitle). World verbs only: no controller parts. */
  readonly text: string;
  /** Subtitle-only control hint shown under the words (button names); never spoken. */
  readonly hint?: string;
  /** Higher speaks first when several lines wait. 10 = openers and the farewell. */
  readonly priority: number;
  /** Dropped and retired for the journey if this holds when its turn comes. */
  readonly unless?: GuideCondition;
  /** Every condition must hold when its turn comes, or the line is dropped (not retired). */
  readonly when?: readonly GuideCondition[];
  /**
   * Toasts this line says first: while it waits or speaks, a matching toast is
   * suppressed (shown after all if the line is dropped). Later toasts, once the line
   * was heard, show as usual. Pattern: 'key:<ToastSystem key>' or text contained in
   * the toast's title or body.
   */
  readonly covers?: readonly string[];
  /** Toasts held back until this line has spoken, then shown (same patterns). */
  readonly defers?: readonly string[];
  /** Speaks on every trigger (each session) instead of once per journey; never saved. */
  readonly repeat?: boolean;
  /** Speaks after the ending (every other line is dropped once the valley is warm). */
  readonly finale?: boolean;
  /** Seconds a queued line may wait before it is dropped as stale (default DEFAULT_TTL, at most MAX_TTL). */
  readonly ttl?: number;
};

/** Context lines go stale quickly; story beats set their own ttl. */
export const DEFAULT_TTL = 20;
/** No line waits longer than this, whatever its ttl. */
export const MAX_TTL = 180;

const NUMBER_WORDS = ['no', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve'];
/** 6 → 'six' (spoken numbers read and sound better than digits). */
export const numberWord = (n: number): string => NUMBER_WORDS[n] ?? String(n);

/**
 * The lines, in rough story order. Each is about 3–12 s spoken: warm and mythic,
 * but concrete about the action and where things are. Prometheus stole fire from
 * the few to give it to everyone; the expedition took it from everyone. Bound to
 * every stolen flame, he guides the keeper to give the Spire's back, and goes free.
 */
export const LINES: readonly GuideLine[] = [
  // ── Arrival: the first how-to within ~10 s, the myth once the fire is lit ──
  {
    id: 'intro', on: ['journey:new+0.8'], priority: 10, ttl: 180, covers: ['key:opening'],
    text: 'Wake, keeper. Your fire is cold. Close your hand on the lighter in your pack, there on the table.',
    hint: 'Squeeze the grip button to hold.',
  },
  {
    id: 'welcome', on: ['journey:resumed+1.5'], priority: 10, repeat: true, ttl: 180, defers: ['key:opening'],
    text: 'You return, keeper. The fire remembers you, even when you do not. Your left wrist shows what the valley asks of you next.',
  },
  {
    id: 'grab', on: ['hand-near', 'done:intro+6'], priority: 8, unless: 'grabbed', ttl: 12,
    text: 'Reach out and close your hand on it, keeper. Open your hand again to let it go.',
    hint: 'Squeeze the grip to hold; release it to let go.',
  },
  // ── First fire ──
  {
    id: 'lighter', on: ['grab:lighter'], priority: 8, unless: 'fire-lit', ttl: 30,
    // The referent is spoken (a voice-only "hold it down" sounds like "lower it"): the finger, then the lighter's flame.
    text: 'Keep your finger pressed: its flame lives only while you do. Hold the lighter\'s flame down in the tinder under the logs.',
    hint: 'Hold the trigger down to keep it lit.',
  },
  {
    id: 'lighter-close', on: ['lighter:on+15'], priority: 7, unless: 'fire-lit', ttl: 15,
    text: 'Closer, keeper. Hold the flame right in the tinder at the heart of the fire, and keep it there.',
    hint: 'Keep the trigger held.',
  },
  {
    id: 'fire', on: ['fire-lit'], priority: 7, unless: 'stew-cooked', ttl: 30,
    text: 'There: the first warmth in many nights. Keep it fed. Now eat: meat and a mushroom from your pack, into the pot.',
  },
  {
    id: 'myth', on: ['done:fire+1.5'], priority: 5, ttl: 120,
    text: 'I am Prometheus, or what is left of him. I stole fire to give it to everyone. Your people took it from everyone.',
  },
  {
    // After the meal, not over the pot: page 1 teaches the torch, the next task. (A keeper
    // who eats something else first, or skips the pot, still hears it.)
    id: 'note', on: ['done:eat+2', 'eat+15', 'done:myth+59'], priority: 4, unless: 'page-read', ttl: 60,
    text: 'In your pack is a note in your own hand. Read it, keeper. It remembers what you cannot.',
    hint: 'Take the page and hold it up to read.',
  },
  {
    id: 'fire-out', on: ['fire-out'], priority: 6, unless: 'fire-lit', covers: ['key:fire-out'],
    text: 'The fire is out. Lay wood in the ring, then wake it again with your lighter.',
  },
  // ── Cooking ──
  {
    id: 'ingredient', on: ['ingredient'], priority: 5, unless: 'stew-cooked', when: ['pot-half'], ttl: 12,
    text: 'Good. One more. Two foods make a stew.',
  },
  {
    id: 'stir', on: ['pot-full'], priority: 6, unless: 'stew-cooked', when: ['at-camp'], covers: ['stir the pot with the spoon'],
    text: 'Now the spoon. Stir the pot in slow circles, two full turns, with the fire alive beneath it.',
  },
  {
    id: 'bowl', on: ['stew-ready'], priority: 6, unless: 'meal-eaten', when: ['at-camp'], ttl: 30, covers: ['key:stew'],
    text: 'It is ready. Dip the bowl into the pot, then raise it to your lips.',
  },
  {
    id: 'eat', on: ['well-fed+1'], priority: 4,
    text: 'Warmth from within. While it lasts you are well fed: your wounds close as you walk, and hunger comes slower.',
  },
  // ── The bench (only at the bench, while the set still waits) ──
  {
    id: 'bench-valid', on: ['bench:valid'], priority: 6, when: ['at-bench', 'bench-ready'], ttl: 15,
    covers: ['Strike the pad three times'],
    text: 'The bench knows this shape. Take the hammer and strike the pad beside the bays, three firm blows.',
  },
  {
    id: 'bench-invalid', on: ['bench:invalid'], priority: 6, when: ['at-bench', 'bench-wrong'], ttl: 15,
    covers: ['fit together'],
    text: 'Those three do not belong together. Take one back and try another. Your pages hold the shapes that work.',
  },
  {
    // The how-to only: lighting it (3–5 s in, for a keeper who read page 1) cuts it as stale.
    id: 'torch', on: ['crafted:torch'], priority: 6, unless: 'torch-lit', ttl: 25,
    text: 'A torch. Hold its head in the fire until it catches.',
  },
  {
    // The warning, once it burns: the only advance notice that carried fire lures the Hollow.
    id: 'torch-lit', on: ['torch-lit+1'], priority: 6, ttl: 40,
    text: 'Carried flame holds back the dark, keeper. But know this: the dark sees it too.',
  },
  {
    id: 'spear', on: ['crafted:spear'], priority: 5, ttl: 25,
    text: 'A spear: thrust it, or throw it and let go. Deer graze in the meadow, down the trail\'s right fork. Go slowly.',
  },
  {
    id: 'bolts', on: ['crafted:bolts'], priority: 5, ttl: 25,
    text: `Bolts, ${numberWord(BOLTS_PER_BUNDLE)} to a bundle. Touch the bundle to a crossbow or a sentry to load it.`,
  },
  {
    id: 'crossbow', on: ['crafted:crossbow'], priority: 5, ttl: 25,
    text: 'Hold it level and loose a bolt with a squeeze of your finger. When it runs dry, touch a bundle of bolts to it.',
    hint: 'Pull the trigger to shoot.',
  },
  {
    id: 'sentry-kit', on: ['crafted:sentry-kit'], priority: 5, unless: 'sentry-built', ttl: 25,
    text: 'Set the kit down low, on open ground near the fire. It will stand and keep watch while you sleep.',
    hint: 'Let go of it close to the ground.',
  },
  // ── Gathering ──
  {
    // Taught when the axe is first taken up (before the first swing), or at the first chop.
    id: 'chop', on: ['grab:axe+0.5', 'chop'], priority: 4,
    text: 'The axe: three strong swings at any trunk shake loose sticks; fallen deadwood gives a log. Split a log on the camp stump for planks.',
  },
  {
    id: 'harvest', on: ['harvest'], priority: 3,
    text: 'The valley gives, and in time it grows back what you take. Carry what you gather home in your pack.',
  },
  {
    id: 'pack', on: ['pack:worn'], priority: 4, covers: ['Pack on your back'],
    text: 'Your pack rides on your back now. Reach over your shoulder to take it down; let it go low, and it unrolls.',
    hint: 'Squeeze the grip behind your shoulder.',
  },
  // ── Night and danger (spoken in the calm, never mid-fight) ──
  {
    // Says the dusk toast and the first "The Hollow stir" toast (both parked on it): one "stay in the light", not three.
    id: 'dusk', on: ['phase:dusk+3'], priority: 7, unless: 'day', covers: ['key:dusk', 'key:stage'],
    text: 'The sun is going. Stay inside the firelight tonight and keep it fed. When the night grows old, rest at the bedroll.',
  },
  {
    id: 'wolf', on: ['done:dusk+1.5', 'wolf'], priority: 7, when: ['wolves-stirring', 'night'], ttl: 120,
    text: 'The Hollow. I knew them as wolves, before the first fire. Your carried flame called them. If one comes close, thrust your torch at it.',
  },
  {
    id: 'hurt', on: ['hurt+0.8'], priority: 7, unless: 'whole', ttl: 25,
    text: 'You are hurt. Eat, and rest by a lit fire; the warmth will close your wounds.',
  },
  {
    id: 'hungry', on: ['hunger-low'], priority: 6, unless: 'fed',
    text: 'Your strength fades with your hunger. Eat soon: berries from the meadow bushes, meat roasted in the flame, or better, a stew.',
  },
  {
    // Urgent (past the threat gate: the fight that causes it) and short.
    id: 'weak', on: ['health-low'], priority: 9, unless: 'healed', ttl: 25,
    text: 'You are close to falling, keeper. Get to the fire, now.',
  },
  {
    id: 'respawn', on: ['respawn+1.5'], priority: 9,
    text: 'Not yet, keeper. An eagle tore me open each day, and each night I was made whole. The fire keeps you the same way.',
  },
  {
    id: 'sleep', on: ['sleep-ready'], priority: 6, unless: 'day', ttl: 30,
    text: 'The night is old now. Go to the bedroll and rest. If you fall, you will wake there.',
    hint: 'Point at the bedroll and pull the trigger.',
  },
  // ── Weapons that guard ──
  {
    id: 'sentry', on: ['sentry-deployed'], priority: 6, covers: ['Sentry set'],
    text: `It stands, ${numberWord(SENTRY_STARTER_BOLTS)} bolts loaded. It looses at any Hollow that comes near. When it runs dry, touch a bundle to it.`,
  },
  {
    id: 'sentry-empty', on: ['sentry-empty'], priority: 7, when: ['sentry-dry'], covers: ['The sentry is empty'],
    text: 'Your sentry is empty. Touch a bolt bundle to it, or it cannot guard you.',
  },
  {
    id: 'crossbow-empty', on: ['crossbow-empty'], priority: 6, covers: ['The crossbow is empty'],
    text: 'Empty. Touch a bundle of bolts to the crossbow to load it.',
  },
  // ── The story (pages are read first: these wait until the page is put down) ──
  {
    id: 'page', on: ['page:1'], priority: 6, ttl: 150,
    text: 'Your own words. The others left pages across the valley. Each gives back a little of what the cold took.',
  },
  {
    id: 'page-2', on: ['page:2'], priority: 6, ttl: 150,
    text: 'They named their venture for me. They learned the stealing, and not the giving.',
  },
  {
    id: 'page-5', on: ['page:5'], priority: 7, ttl: 150,
    text: 'Now you know what you carry. I was chained for a stolen fire once. Give this one back, keeper, and we both go free.',
  },
  {
    id: 'page-7', on: ['page:7'], priority: 8, ttl: 150,
    text: 'She stayed when the others fled. Do as she asked: bring a lit torch here, into the beacon, and do not let go.',
  },
  // ── The Spire ──
  {
    // 'beacon-cold' is watched by the GuideSystem (a lit torch in the beacon before page 5 is read), not read off a toast.
    id: 'beacon-cold', on: ['beacon-cold'], priority: 7, covers: ['The beacon stays cold'],
    text: 'The stone will not take it from a stranger. Remember what you did, keeper. Your people’s notes wait at the outpost below.',
  },
  {
    // Says the covered toast's rule (the only place it lived): the defence is the other hand.
    id: 'beacon', on: ['beacon'], priority: 9, ttl: 8, covers: ['Hold the flame steady'],
    text: 'Hold it there, keeper. They will try to smother it: keep your other hand free to drive them off.',
  },
  {
    // The hold slips (let go, or the guardians press on the stone): past the threat gate, once.
    // It leads with the fix for both causes, never an order ("let go") heard mid-fight.
    id: 'beacon-slip', on: ['beacon-slip'], priority: 9, ttl: 10,
    text: 'It is cooling, keeper. Keep your flame in the stone, and drive them from it.',
  },
  {
    id: 'ending', on: ['ending-step:smoke+6'], priority: 10, finale: true, ttl: 60,
    text: 'Look back the way you came: smoke. Someone made it out. The fire is everyone\'s again, and I am free. Go home, keeper. Yours is burning.',
  },
];

/**
 * Trigger keys the GuideSystem raises by watching state (not from a bus event):
 * 'beacon-cold' (a lit torch held in the beacon before page 5 is read) and
 * 'beacon-slip' (the beacon's progress falling after it passed BEACON_SLIP_FROM).
 */
export const POLLED_TRIGGERS = ['hand-near', 'pot-full', 'hunger-low', 'health-low', 'sleep-ready', 'beacon-cold', 'beacon-slip'] as const;
/** The beacon-slip line waits until the hold has got this far (Beacon.progress). */
export const BEACON_SLIP_FROM = 0.25;

/** Thresholds for the polled triggers and the stale checks. */
export const GUIDE_THRESHOLDS = {
  hungerLow: 25, fed: 40,
  healthLow: 30, healed: 45, whole: 95,
  /** A hand this close (m) to a loose item counts as reaching for it. */
  handNear: 0.28,
  /** Within this distance (m) of the bench the player can act on a bench line. */
  benchReach: 3.5,
  /** Within this distance (m) of the campfire the player is at camp (the pot lines). */
  campReach: 10,
} as const;

/** Wood that chopping yields; its 'harvest' events are covered by the chop line. */
const WOOD = new Set(['log', 'stick', 'plank', 'deadwood']);
const WOLF_CUES = new Set(['howl', 'spawn', 'stalk', 'growl', 'bite']);

/**
 * Bus event → trigger keys (written into `out`, which is cleared first). Pure:
 * the GuideSystem calls it for every event and looks the keys up in TRIGGERS.
 */
export function triggersOf(event: GameEvent, out: string[] = []): string[] {
  out.length = 0;
  switch (event.type) {
    case 'journey-begin': out.push(event.resumed ? 'journey:resumed' : 'journey:new'); break;
    case 'grab': out.push('grab', `grab:${event.kind}`); break;
    case 'lighter': if (event.lit) out.push('lighter:on'); break;
    case 'fire-lit': out.push('fire-lit'); break;
    case 'fire-out': out.push('fire-out'); break;
    case 'ingredient': out.push('ingredient'); break;
    case 'stew-ready': out.push('stew-ready'); break;
    case 'eat': out.push('eat'); break;
    case 'well-fed': if (event.seconds > 0) out.push('well-fed'); break;
    case 'bench-set': out.push(event.valid ? 'bench:valid' : 'bench:invalid'); break;
    case 'crafted': out.push(`crafted:${event.product}`); break;
    case 'torch-lit': out.push('torch-lit'); break;
    case 'page': if (event.first) out.push('page', `page:${event.index}`); break;
    case 'chop': out.push('chop'); break;
    case 'harvest': if (!WOOD.has(event.kind)) out.push('harvest'); break;
    case 'pack': out.push(`pack:${event.state}`); break;
    case 'phase': out.push(`phase:${event.phase}`); break;
    case 'creature': if (event.species === 'wolf' && WOLF_CUES.has(event.cue)) out.push('wolf'); break;
    case 'hurt': out.push('hurt'); break;
    case 'respawn': out.push('respawn'); break;
    case 'sentry-deployed': out.push('sentry-deployed'); break;
    case 'sentry-empty': out.push('sentry-empty'); break;
    case 'crossbow-empty': out.push('crossbow-empty'); break;
    case 'beacon': if (!event.lit && event.progress > 0) out.push('beacon'); break;
    case 'ending-step': out.push(`ending-step:${event.step}`); break;
    default: break;
  }
  return out;
}

export type TriggerRef = { readonly line: GuideLine; readonly delay: number };

/** 'done:intro+6' → { key: 'done:intro', delay: 6 }. */
export function parseTrigger(trigger: string): { key: string; delay: number } {
  const plus = trigger.lastIndexOf('+');
  if (plus < 0) return { key: trigger, delay: 0 };
  return { key: trigger.slice(0, plus), delay: Number(trigger.slice(plus + 1)) };
}

/** Trigger key → the lines it can start (with their delays). */
export const TRIGGERS: ReadonlyMap<string, readonly TriggerRef[]> = (() => {
  const map = new Map<string, TriggerRef[]>();
  for (const line of LINES) {
    for (const trigger of line.on) {
      const { key, delay } = parseTrigger(trigger);
      let list = map.get(key);
      if (!list) map.set(key, list = []);
      list.push({ line, delay });
    }
  }
  return map;
})();

export const lineById = (id: string): GuideLine | undefined => LINES.find((line) => line.id === id);

/** Seconds a queued line may wait (its ttl, capped). */
export const lineTtl = (line: GuideLine): number => Math.min(MAX_TTL, line.ttl ?? DEFAULT_TTL);

/** Estimated spoken length (s) of a line whose clip is not available. */
export function estimateSeconds(text: string): number {
  const words = text.trim().split(/\s+/).length;
  return Math.round((0.6 + words / WORDS_PER_SECOND) * 10) / 10;
}

/**
 * Whether a toast matches one of a line's patterns: 'key:<k>' compares the
 * ToastSystem's message key; any other pattern is looked for in the title and body.
 */
export function toastMatches(patterns: readonly string[] | undefined, title: string, body: string, key: string): boolean {
  if (!patterns) return false;
  for (let i = 0; i < patterns.length; i++) {
    const pattern = patterns[i];
    if (pattern.startsWith('key:')) {
      if (key === pattern.slice(4)) return true;
    } else if (title.includes(pattern) || body.includes(pattern)) {
      return true;
    }
  }
  return false;
}

// ─── GameState.guide: comma-separated ids spoken this journey ───

/** Whether `id` is in the comma-separated list (no allocation). */
export function hasSpoken(list: string, id: string): boolean {
  let from = 0;
  for (;;) {
    const at = list.indexOf(id, from);
    if (at < 0) return false;
    const end = at + id.length;
    if ((at === 0 || list.charCodeAt(at - 1) === 44) && (end === list.length || list.charCodeAt(end) === 44)) return true;
    from = end;
  }
}

export const addSpoken = (list: string, id: string): string =>
  (hasSpoken(list, id) ? list : list ? `${list},${id}` : id);

/** The list without `id` (a line cut early is spoken again later). */
export const removeSpoken = (list: string, id: string): string =>
  (hasSpoken(list, id) ? list.split(',').filter((entry) => entry !== id).join(',') : list);

// ─── Voice clips ───

/** The Drawcall speech request for a line (the input `speech()` receives): the words only, never the hint. */
export const speechInput = (line: GuideLine) => ({ text: line.text, voice: VOICE.voice, style: VOICE.style });

/** Asset-manifest id of a line's clip. */
export const clipId = (id: string) => `voice-${id}`;

/** Batch number (1-based) of the line at `index` on the voice-prep page. */
export const prepBatchOf = (index: number) => Math.floor(index / PREP_BATCH) + 1;
export const PREP_BATCHES = Math.ceil(LINES.length / PREP_BATCH);
