/**
 * GENERATED by `node scripts/voice-urls.mjs` from voice-lines.ts: do not edit.
 *
 * The Drawcall content hash of each guide line's speech request ({ text, voice,
 * style }), exactly as @drawcall/generate computes it, so the runtime never bundles
 * the package (zod, @noble/hashes). A clip lives at `${origin}/assets/${hash}` (404
 * until voice-prep.html has generated it). tests/voice-lines.test.mjs fails when
 * this file is stale: run the script again after editing a line's text or the voice.
 */
export const VOICE_HASHES: Readonly<Record<string, string>> = {
  intro: 'ce73fa4cc85e8f4d74f5eeb7f621890fa8daf78b08326f9b0581f4989ecca3d6',
  welcome: '528916812a1033870761fa33c5afcee0dcb1b2e7b82e0a7cf74206df121bc82b',
  grab: 'c8d24fae39bc784d2b8cb849e73e84b07108d6d53495522128b001689434874c',
  lighter: '5c60c3c892c56cfb538f36facdb31ca1421f0ba7fd7fa28188b04dd3ccb91b53',
  'lighter-close': '2a40f3b1cf050ce66dc0fae346390dc751bec3d49d71e84c970ac6940d4c7bff',
  fire: 'ab3dea24d98c91e3e270d7b5585f04bb56ed7052bbac0c6d6f3f3a5f32746a05',
  myth: 'b5d7758bbdb85d9e2fe48294b1e42fcf41141ddfe846d1c644d327f4273fd733',
  note: '3b3274ea878c55d2a1bc051fd97769fa8fa9957d5867713ce65476b643135dc3',
  'fire-out': 'fd548a9e747026245e3642c807d402d983825895ce38f8f37b997f93964582ff',
  ingredient: '9e120f81f83b56aea41d5d5f735797f233c4b207602fac510114d689a578c5dd',
  stir: 'f44ab7fd2f49b721c81364e924a1ec9604364445ae851157e21241a6c4bd30d4',
  bowl: '5dd3adb307cb3731462ad431192d62c112c6f99c03f331e9ab7d7e7c1e936f57',
  eat: 'b168f3d6939f4532ab2a00005525484a91976f5fe0a4f53b8ccf2ae2b01844e5',
  'bench-valid': 'a21619e28db5670ba1ec5c654d196c6f8bf76ac610c98be34e0071aa02ba9d48',
  'bench-invalid': '3c0d07a315d10cea35db5e87bc42b776f36dc04644c2b97183f552f1636bc667',
  torch: '4c79d71070244aad9f0416b2f3442e2f491f882db00d59f296a7be585bc0fa7e',
  'torch-lit': '45121a0f0a87053a66de207349152989102c0093ce54a0747cde80d6b8b6623b',
  spear: '25d59027a450a8bd4adf1984178b26becf4058f6540c88fb6f1393e48dd8dd3c',
  bolts: 'ff8cb3775c82bd44447413980351404923b7df2ecb181d981ad44a90fafa1365',
  crossbow: '76e62ec59e07b25c15332406c5bb2dd0738ba663fb4265235e2e6dba54b764b0',
  'sentry-kit': 'c2b0d401864bdcb3444367c98f023c1a071015f21dd65cc5c6ea484c8f648ada',
  chop: '59a72c4016d0687d1da3dd9f21ef9595d6f91fd4a5f87f471553a5e5352fe232',
  harvest: 'a968004013ad4d2fdf58e457533d9d40f743e77750a577eb173dcf185b5f1222',
  pack: 'c3cf6b01d799e15fddaa85a212ceac8d399d28d15d4dc116c9034a7580182927',
  dusk: '0c55083f7c2afbe67e0b58ef569736144a2cc32ac9e826d6c9f1fa1c0c3ab8ce',
  wolf: '4e5a12314369367003d3a956cea25ae19fc9378243c1fd2e2c79aa7ea4aec4c3',
  hurt: 'dfc3b3c3e9b5e7ed1d17b1e349cc01a2e10cf8d5341002840461b89e04fb5fd6',
  hungry: '04639dd3a641d7290c09cefef0d1a06dde7815b5c157c31b5b7132801c6b96b7',
  weak: '8fcafd6492305ebcbccbe04ab2d1ceebb580a9c8be86712dbf29f7f5e45388f3',
  respawn: 'b64d78e2f0572bfc2adcd31570c5b188463bc633d809c1ac7d5420edcf5062ee',
  sleep: '04646706064009f2d93f34d39b9944ca0f5c96bb4dc06be9c7e45cfccd6b51dc',
  sentry: '28ce39f189e12141a520b4c0ce565c725addce43b13a8fa8ae50a903eb56007a',
  'sentry-empty': 'c89c690b1d3798defc1a3a5f118ec1d6c07e3a40bd858c2016c26e277e124d4f',
  'crossbow-empty': 'f41080e807bbe5777a9f345f38b757fbd2b50765309d80d1914ae9f52a1ebac1',
  page: 'dbcf16225c551518f738ada8f12cf5e8c128bf02887751c109012d8727751f2d',
  'page-2': '0f99a7e6a0731f141706dabbbf6f6037157bcb1e56c36d5212d58d74115970b5',
  'page-5': '697e80df5829bf47154b317cef4d9979d92821d7562c5d90846e573385f7bfa9',
  'page-7': 'e6065710dcc1d64a8718dfc747ebfaccab2be66632bd016efd1b29d1b0cc01a5',
  'beacon-cold': '94960f5cde086ae86f1208fe9c4429a5aa23ed0fbb4e3eebee0b0f3e358e2aac',
  beacon: 'ea110c45ab94f31ffe1281e76548ccd7a6d1ea044d18299474be0147ba6fdee2',
  'beacon-slip': '4291870cc14e4abe1c61490d01bb3553f9ef651c53b684c12129b6971c962a05',
  ending: 'ec20083c4d1d1332509e266691974c16970c30e1a176bd82f6ae6ed5c316f04a',
};

/** Where a line's clip lives (the package's assetUrl). */
export const voiceClipUrl = (hash: string, origin: string): string => new URL(`/assets/${hash}`, origin).href;
