#!/usr/bin/env node
/**
 * Writes src/game/voice-urls.ts: the Drawcall content hash of every guide line's
 * speech request ({ text, voice, style }), computed by @drawcall/generate itself.
 *
 * The game imports that static module instead of the package, so the runtime bundle
 * never carries zod or @noble/hashes; only the dev-only voice-prep page imports the
 * package. Run it after editing a line's text or the voice:
 *
 *   node scripts/voice-urls.mjs          # rewrite the module
 *   node scripts/voice-urls.mjs --check  # exit 1 if it is stale (no write)
 *
 * tests/voice-lines.test.mjs makes the same comparison, so a stale module fails `npm test`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { requestHash, speechSchema } from '@drawcall/generate';
import { loadTs } from '../tests/helpers/load-ts.mjs';

const target = fileURLToPath(new URL('../src/game/voice-urls.ts', import.meta.url));
const voice = await loadTs('src/game/voice-lines.ts');

/** The hash @drawcall/generate's `speech()` gives a line's request. */
export const hashOf = (line) => requestHash({ type: 'speech', input: speechSchema.parse(voice.speechInput(line)) });

const rows = voice.LINES.map((line) => `  ${/^[a-z][a-z0-9]*$/.test(line.id) ? line.id : `'${line.id}'`}: '${hashOf(line)}',`);
const source = `/**
 * GENERATED by \`node scripts/voice-urls.mjs\` from voice-lines.ts: do not edit.
 *
 * The Drawcall content hash of each guide line's speech request ({ text, voice,
 * style }), exactly as @drawcall/generate computes it, so the runtime never bundles
 * the package (zod, @noble/hashes). A clip lives at \`\${origin}/assets/\${hash}\` (404
 * until voice-prep.html has generated it). tests/voice-lines.test.mjs fails when
 * this file is stale: run the script again after editing a line's text or the voice.
 */
export const VOICE_HASHES: Readonly<Record<string, string>> = {
${rows.join('\n')}
};

/** Where a line's clip lives (the package's assetUrl). */
export const voiceClipUrl = (hash: string, origin: string): string => new URL(\`/assets/\${hash}\`, origin).href;
`;

let current = '';
try { current = readFileSync(target, 'utf8'); } catch { /* first run */ }
if (process.argv.includes('--check')) {
  if (current !== source) {
    console.error('src/game/voice-urls.ts is stale: run `node scripts/voice-urls.mjs`.');
    process.exit(1);
  }
  console.log(`voice-urls.ts is current (${voice.LINES.length} lines).`);
} else if (current === source) {
  console.log(`voice-urls.ts is already current (${voice.LINES.length} lines).`);
} else {
  writeFileSync(target, source);
  console.log(`Wrote src/game/voice-urls.ts (${voice.LINES.length} lines).`);
}
